import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Import generated mocks
import 'mocks.mocks.dart';

// Generate mocks for debugging test infrastructure
@GenerateMocks([
  // Cache services
  SharedPreferences,
])
void main() {
  // Mock generation placeholder - actual mocks generated by build_runner
}

/// Mock utilities for debugging tests
class MockTestUtilities {
  /// Create a mock SharedPreferences with debugging data
  static MockSharedPreferences createMockPreferencesWithDebuggingData() {
    final mock = MockSharedPreferences();
    
    // Set up typical debugging cache data
    when(mock.getDouble('manual_location_lat')).thenReturn(57.2);
    when(mock.getDouble('manual_location_lon')).thenReturn(-3.8);
    when(mock.getString('manual_location_place')).thenReturn('Aviemore (Debug)');
    when(mock.getString('location_timestamp')).thenReturn('2025-10-07T12:00:00Z');
    when(mock.getString('location_source')).thenReturn('DEBUG_BYPASS');
    when(mock.getBool('test_mode')).thenReturn(true);
    
    return mock;
  }
  
  /// Create a mock SharedPreferences with cleared cache
  static MockSharedPreferences createMockPreferencesWithClearedCache() {
    final mock = MockSharedPreferences();
    
    // All location keys return null (cleared state)
    when(mock.getDouble('manual_location_lat')).thenReturn(null);
    when(mock.getDouble('manual_location_lon')).thenReturn(null);
    when(mock.getString('manual_location_place')).thenReturn(null);
    when(mock.getString('location_timestamp')).thenReturn(null);
    when(mock.getString('location_source')).thenReturn(null);
    when(mock.getBool('test_mode')).thenReturn(true); // Preserved
    
    return mock;
  }
  
  /// Create GPS bypass test data
  static Map<String, dynamic> createGpsTestData() {
    return {
      'bypass_active': true,
      'expected_lat': DebugTestConstants.aviemoreLat,
      'expected_lon': DebugTestConstants.aviemoreLon,
      'gps_should_not_be_called': true,
    };
  }
}

/// Test constants for debugging scenarios
class DebugTestConstants {
  static const double aviemoreLat = 57.2;
  static const double aviemoreLon = -3.8;
  static const double scotlandCentroidLat = 55.8642;
  static const double scotlandCentroidLon = -4.2518;
  
  static const List<String> cacheKeys = [
    'manual_location_lat',
    'manual_location_lon', 
    'manual_location_place',
    'location_timestamp',
    'location_source',
  ];
  
  static const String testMode = 'test_mode';
}