// Mocks generated by Mockito 5.4.6 from annotations
// in wildfire_mvp_v3/test/unit/services/fire_location_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wildfire_mvp_v3/models/api_error.dart' as _i5;
import 'package:wildfire_mvp_v3/models/effis_fire.dart' as _i7;
import 'package:wildfire_mvp_v3/models/effis_fwi_result.dart' as _i6;
import 'package:wildfire_mvp_v3/models/fire_incident.dart' as _i10;
import 'package:wildfire_mvp_v3/models/lat_lng_bounds.dart' as _i8;
import 'package:wildfire_mvp_v3/services/effis_service.dart' as _i3;
import 'package:wildfire_mvp_v3/services/mock_fire_service.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EffisService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEffisService extends _i1.Mock implements _i3.EffisService {
  MockEffisService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ApiError, _i6.EffisFwiResult>> getFwi({
    required double? lat,
    required double? lon,
    Duration? timeout = const Duration(seconds: 30),
    int? maxRetries = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFwi, [], {
              #lat: lat,
              #lon: lon,
              #timeout: timeout,
              #maxRetries: maxRetries,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.ApiError, _i6.EffisFwiResult>>.value(
                  _FakeEither_0<_i5.ApiError, _i6.EffisFwiResult>(
                    this,
                    Invocation.method(#getFwi, [], {
                      #lat: lat,
                      #lon: lon,
                      #timeout: timeout,
                      #maxRetries: maxRetries,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.ApiError, _i6.EffisFwiResult>>);

  @override
  _i4.Future<_i2.Either<_i5.ApiError, List<_i7.EffisFire>>> getActiveFires(
    _i8.LatLngBounds? bounds, {
    Duration? timeout = const Duration(seconds: 8),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveFires, [bounds], {#timeout: timeout}),
            returnValue:
                _i4.Future<_i2.Either<_i5.ApiError, List<_i7.EffisFire>>>.value(
                  _FakeEither_0<_i5.ApiError, List<_i7.EffisFire>>(
                    this,
                    Invocation.method(
                      #getActiveFires,
                      [bounds],
                      {#timeout: timeout},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.ApiError, List<_i7.EffisFire>>>);
}

/// A class which mocks [MockFireService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockFireService extends _i1.Mock implements _i9.MockFireService {
  MockMockFireService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ApiError, List<_i10.FireIncident>>> getActiveFires(
    _i8.LatLngBounds? bounds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveFires, [bounds]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.ApiError, List<_i10.FireIncident>>
                >.value(
                  _FakeEither_0<_i5.ApiError, List<_i10.FireIncident>>(
                    this,
                    Invocation.method(#getActiveFires, [bounds]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.ApiError, List<_i10.FireIncident>>>);
}
