// Mocks generated by Mockito 5.4.6 from annotations
// in wildfire_mvp_v3/test/unit/controllers/onboarding_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wildfire_mvp_v3/models/consent_record.dart' as _i5;
import 'package:wildfire_mvp_v3/models/location_models.dart' as _i7;
import 'package:wildfire_mvp_v3/services/location_resolver.dart' as _i6;
import 'package:wildfire_mvp_v3/services/onboarding_prefs.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OnboardingPrefsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingPrefsService extends _i1.Mock
    implements _i3.OnboardingPrefsService {
  MockOnboardingPrefsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> isOnboardingRequired() => (super.noSuchMethod(
        Invocation.method(
          #isOnboardingRequired,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isMigrationRequired() => (super.noSuchMethod(
        Invocation.method(
          #isMigrationRequired,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> getOnboardingVersion() => (super.noSuchMethod(
        Invocation.method(
          #getOnboardingVersion,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i5.ConsentRecord?> getConsentRecord() => (super.noSuchMethod(
        Invocation.method(
          #getConsentRecord,
          [],
        ),
        returnValue: _i4.Future<_i5.ConsentRecord?>.value(),
      ) as _i4.Future<_i5.ConsentRecord?>);

  @override
  _i4.Future<int> getNotificationRadiusKm() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationRadiusKm,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getPreviousVersion() => (super.noSuchMethod(
        Invocation.method(
          #getPreviousVersion,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> completeOnboarding({required int? radiusKm}) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeOnboarding,
          [],
          {#radiusKm: radiusKm},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateNotificationRadius({required int? radiusKm}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotificationRadius,
          [],
          {#radiusKm: radiusKm},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetOnboarding() => (super.noSuchMethod(
        Invocation.method(
          #resetOnboarding,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [LocationResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationResolver extends _i1.Mock implements _i6.LocationResolver {
  MockLocationResolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i7.LocationError, _i7.ResolvedLocation>> getLatLon(
          {bool? allowDefault = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatLon,
          [],
          {#allowDefault: allowDefault},
        ),
        returnValue: _i4
            .Future<_i2.Either<_i7.LocationError, _i7.ResolvedLocation>>.value(
            _FakeEither_0<_i7.LocationError, _i7.ResolvedLocation>(
          this,
          Invocation.method(
            #getLatLon,
            [],
            {#allowDefault: allowDefault},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.LocationError, _i7.ResolvedLocation>>);

  @override
  _i4.Future<void> saveManual(
    _i7.LatLng? location, {
    String? placeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveManual,
          [location],
          {#placeName: placeName},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearManualLocation() => (super.noSuchMethod(
        Invocation.method(
          #clearManualLocation,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<(_i7.LatLng, String?)?> loadCachedManualLocation() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadCachedManualLocation,
          [],
        ),
        returnValue: _i4.Future<(_i7.LatLng, String?)?>.value(),
      ) as _i4.Future<(_i7.LatLng, String?)?>);
}
