// Mocks generated by Mockito 5.4.6 from annotations
// in wildfire_mvp_v3/test/widget/fire_risk_navigation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wildfire_mvp_v3/models/api_error.dart' as _i5;
import 'package:wildfire_mvp_v3/models/location_models.dart' as _i8;
import 'package:wildfire_mvp_v3/services/fire_risk_service.dart' as _i3;
import 'package:wildfire_mvp_v3/services/location_resolver.dart' as _i7;
import 'package:wildfire_mvp_v3/services/models/fire_risk.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [FireRiskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFireRiskService extends _i1.Mock implements _i3.FireRiskService {
  MockFireRiskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ApiError, _i6.FireRisk>> getCurrent({
    required double? lat,
    required double? lon,
    Duration? deadline,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getCurrent, [], {
          #lat: lat,
          #lon: lon,
          #deadline: deadline,
        }),
        returnValue: _i4.Future<_i2.Either<_i5.ApiError, _i6.FireRisk>>.value(
          _FakeEither_0<_i5.ApiError, _i6.FireRisk>(
            this,
            Invocation.method(#getCurrent, [], {
              #lat: lat,
              #lon: lon,
              #deadline: deadline,
            }),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i5.ApiError, _i6.FireRisk>>);
}

/// A class which mocks [LocationResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationResolver extends _i1.Mock implements _i7.LocationResolver {
  MockLocationResolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i8.LocationError, _i8.ResolvedLocation>> getLatLon({
    bool? allowDefault = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getLatLon, [], {#allowDefault: allowDefault}),
        returnValue: _i4
            .Future<_i2.Either<_i8.LocationError, _i8.ResolvedLocation>>.value(
          _FakeEither_0<_i8.LocationError, _i8.ResolvedLocation>(
            this,
            Invocation.method(#getLatLon, [], {
              #allowDefault: allowDefault,
            }),
          ),
        ),
      ) as _i4.Future<_i2.Either<_i8.LocationError, _i8.ResolvedLocation>>);

  @override
  _i4.Future<void> saveManual(_i8.LatLng? location, {String? placeName}) =>
      (super.noSuchMethod(
        Invocation.method(#saveManual, [location], {#placeName: placeName}),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearManualLocation() => (super.noSuchMethod(
        Invocation.method(#clearManualLocation, []),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<(_i8.LatLng, String?)?> loadCachedManualLocation() =>
      (super.noSuchMethod(
        Invocation.method(#loadCachedManualLocation, []),
        returnValue: _i4.Future<(_i8.LatLng, String?)?>.value(),
      ) as _i4.Future<(_i8.LatLng, String?)?>);
}
