// Mocks generated by Mockito 5.4.6 from annotations
// in wildfire_mvp_v3/test/integration/fire_risk_service_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wildfire_mvp_v3/models/api_error.dart' as _i5;
import 'package:wildfire_mvp_v3/models/effis_fwi_result.dart' as _i6;
import 'package:wildfire_mvp_v3/services/contracts/service_contracts.dart'
    as _i3;
import 'package:wildfire_mvp_v3/services/models/fire_risk.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOption_1<A> extends _i1.SmartFake implements _i2.Option<A> {
  _FakeOption_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EffisService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEffisService extends _i1.Mock implements _i3.EffisService {
  MockEffisService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ApiError, _i6.EffisFwiResult>> getFwi({
    required double? lat,
    required double? lon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFwi,
          [],
          {
            #lat: lat,
            #lon: lon,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.ApiError, _i6.EffisFwiResult>>.value(
                _FakeEither_0<_i5.ApiError, _i6.EffisFwiResult>(
          this,
          Invocation.method(
            #getFwi,
            [],
            {
              #lat: lat,
              #lon: lon,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ApiError, _i6.EffisFwiResult>>);
}

/// A class which mocks [SepaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSepaService extends _i1.Mock implements _i3.SepaService {
  MockSepaService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ApiError, _i7.FireRisk>> getCurrent({
    required double? lat,
    required double? lon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrent,
          [],
          {
            #lat: lat,
            #lon: lon,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.ApiError, _i7.FireRisk>>.value(
            _FakeEither_0<_i5.ApiError, _i7.FireRisk>(
          this,
          Invocation.method(
            #getCurrent,
            [],
            {
              #lat: lat,
              #lon: lon,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ApiError, _i7.FireRisk>>);
}

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i3.CacheService {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Option<_i7.FireRisk>> get({required String? key}) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {#key: key},
        ),
        returnValue: _i4.Future<_i2.Option<_i7.FireRisk>>.value(
            _FakeOption_1<_i7.FireRisk>(
          this,
          Invocation.method(
            #get,
            [],
            {#key: key},
          ),
        )),
      ) as _i4.Future<_i2.Option<_i7.FireRisk>>);

  @override
  _i4.Future<void> set({
    required String? key,
    required _i7.FireRisk? value,
    required Duration? ttl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [],
          {
            #key: key,
            #value: value,
            #ttl: ttl,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
