// Mocks generated by Mockito 5.4.6 from annotations
// in wildfire_mvp_v3/test/integration/map_controller_fallback_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wildfire_mvp_v3/models/api_error.dart' as _i7;
import 'package:wildfire_mvp_v3/models/burnt_area.dart' as _i13;
import 'package:wildfire_mvp_v3/models/fire_data_mode.dart' as _i14;
import 'package:wildfire_mvp_v3/models/fire_incident.dart' as _i8;
import 'package:wildfire_mvp_v3/models/lat_lng_bounds.dart' as _i9;
import 'package:wildfire_mvp_v3/models/location_models.dart' as _i5;
import 'package:wildfire_mvp_v3/services/effis_burnt_area_service.dart' as _i12;
import 'package:wildfire_mvp_v3/services/fire_location_service.dart' as _i6;
import 'package:wildfire_mvp_v3/services/fire_risk_service.dart' as _i10;
import 'package:wildfire_mvp_v3/services/location_resolver.dart' as _i3;
import 'package:wildfire_mvp_v3/services/models/fire_risk.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocationResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationResolver extends _i1.Mock implements _i3.LocationResolver {
  MockLocationResolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.LocationError, _i5.ResolvedLocation>> getLatLon(
          {bool? allowDefault = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatLon,
          [],
          {#allowDefault: allowDefault},
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.LocationError, _i5.ResolvedLocation>>.value(
            _FakeEither_0<_i5.LocationError, _i5.ResolvedLocation>(
          this,
          Invocation.method(
            #getLatLon,
            [],
            {#allowDefault: allowDefault},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.LocationError, _i5.ResolvedLocation>>);

  @override
  _i4.Future<void> saveManual(
    _i5.LatLng? location, {
    String? placeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveManual,
          [location],
          {#placeName: placeName},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearManualLocation() => (super.noSuchMethod(
        Invocation.method(
          #clearManualLocation,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<(_i5.LatLng, String?)?> loadCachedManualLocation() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadCachedManualLocation,
          [],
        ),
        returnValue: _i4.Future<(_i5.LatLng, String?)?>.value(),
      ) as _i4.Future<(_i5.LatLng, String?)?>);
}

/// A class which mocks [FireLocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFireLocationService extends _i1.Mock
    implements _i6.FireLocationService {
  MockFireLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i7.ApiError, List<_i8.FireIncident>>> getActiveFires(
          _i9.LatLngBounds? bounds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveFires,
          [bounds],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.ApiError, List<_i8.FireIncident>>>.value(
                _FakeEither_0<_i7.ApiError, List<_i8.FireIncident>>(
          this,
          Invocation.method(
            #getActiveFires,
            [bounds],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.ApiError, List<_i8.FireIncident>>>);
}

/// A class which mocks [FireRiskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFireRiskService extends _i1.Mock implements _i10.FireRiskService {
  MockFireRiskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i7.ApiError, _i11.FireRisk>> getCurrent({
    required double? lat,
    required double? lon,
    Duration? deadline,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrent,
          [],
          {
            #lat: lat,
            #lon: lon,
            #deadline: deadline,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i7.ApiError, _i11.FireRisk>>.value(
            _FakeEither_0<_i7.ApiError, _i11.FireRisk>(
          this,
          Invocation.method(
            #getCurrent,
            [],
            {
              #lat: lat,
              #lon: lon,
              #deadline: deadline,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.ApiError, _i11.FireRisk>>);
}

/// A class which mocks [EffisBurntAreaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEffisBurntAreaService extends _i1.Mock
    implements _i12.EffisBurntAreaService {
  MockEffisBurntAreaService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i7.ApiError, List<_i13.BurntArea>>> getBurntAreas({
    required _i9.LatLngBounds? bounds,
    required _i14.BurntAreaSeasonFilter? seasonFilter,
    Duration? timeout = const Duration(seconds: 10),
    int? maxRetries = 3,
    int? maxFeatures,
    bool? skipLiveApi = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBurntAreas,
          [],
          {
            #bounds: bounds,
            #seasonFilter: seasonFilter,
            #timeout: timeout,
            #maxRetries: maxRetries,
            #maxFeatures: maxFeatures,
            #skipLiveApi: skipLiveApi,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.ApiError, List<_i13.BurntArea>>>.value(
                _FakeEither_0<_i7.ApiError, List<_i13.BurntArea>>(
          this,
          Invocation.method(
            #getBurntAreas,
            [],
            {
              #bounds: bounds,
              #seasonFilter: seasonFilter,
              #timeout: timeout,
              #maxRetries: maxRetries,
              #maxFeatures: maxFeatures,
              #skipLiveApi: skipLiveApi,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.ApiError, List<_i13.BurntArea>>>);
}
